changelog:
  categories:
    - title: What's Changed ğŸ•
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: ğŸ‘’ Dependencies
      labels:
        - dependencies
